version: '3.8'

services:
  php:
    container_name: loan_php
    restart: unless-stopped
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    working_dir: /app